{% set name = "slack-sdk" %}
{% set version = "3.33.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slack_sdk-{{ version }}.tar.gz
  sha256: 5e109847f6b6a22d227609226ba4ed936109dc00675bddeb7e0bee502d3ee7e0

build:
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}

outputs:
  - name: slack-sdk
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - python >={{ python_min }}
    test:
      imports:
        - slack_sdk
        - slack_sdk.web
        - slack_sdk.webhook
        - slack_sdk.signature
        - slack_sdk.socket_mode
        - slack_sdk.audit_logs
        - slack_sdk.scim
        - slack_sdk.oauth
        - slack_sdk.models
        # The old RTM API has a dependency on aiohttp
        - slack_sdk.rtm
        - slack_sdk.rtm_v2
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip
        - aiohttp
  - name: slack_sdk
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - slack_sdk
      requires:
        - python {{ python_min }}

about:
  home: https://github.com/slackapi/python-slack-sdk
  summary: The Slack API Platform SDK for Python
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/slackapi/python-slack-sdk
  doc_url: https://github.com/slackapi/python-slack-sdk

extra:
  recipe-maintainers:
    - xylar
    - maresb
